// Copyright 2026 Plamen K. Kosseff
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package zsh

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"sxcli.dev/completion/engine"
	genscript "sxcli.dev/completion/script"
	sxclifw "sxcli.dev/fw"
)

func init() {
	c := &Completion{}
	sxclifw.Register("completionzsh", c,
		sxclifw.System(),
		sxclifw.WithConfig(&c.cfg),
		sxclifw.WithMetadata(&sxclifw.Metadata{
			Description: "zsh completion for this binary: --script prints the compdef registration for the name the binary was invoked as, completion queries arrive as zsh words/CURRENT/PREFIX and are answered as _describe pairs on stdout",
		}),
	)
}

// Configured validates nothing: the query fields are per-invocation
// transport with no illegal states the parser does not already refuse.
func (c *Completion) Configured() error { return nil }

// Run answers the operation selected by the arguments: --script
// emission, or a completion query. Queries always exit 0 — a
// completion must never look like a failure.
func (c *Completion) Run() int {
	if c.cfg.Script {
		script(os.Stdout, c.I, os.Args[0])
	} else {
		answer(os.Stdout, c.I, c.cfg, sxclifw.Positionals())
	}
	return 0
}

// scriptTemplate is the emitted registration: deliberately dumb zsh.
// Candidates arrive as _describe-ready value:description lines; the
// file and directory directives arrive as \001-sentinel lines and map
// to _files. Nothing declared means _default — the shell's own file
// completion, mirroring the engine's silence contract.
const scriptTemplate = `# zsh completion for %[1]s, generated by: %[1]s completionzsh --script
# requires compinit to have been run
%[2]s() {
    local -a lines pairs
    local line
    lines=("${(@f)$("${words[1]}" completionzsh%[3]s --cword $((CURRENT-1)) --current "$PREFIX" -- "${(@)words}" 2>/dev/null)}")
    pairs=()
    for line in "${lines[@]}"; do
        case "$line" in
            $'\001files') _files; return ;;
            $'\001dirs')  _files -/; return ;;
            '') ;;
            *) pairs+=("$line") ;;
        esac
    done
    if (( ${#pairs} )); then
        _describe 'completions' pairs
    else
        _default
    fi
}
compdef %[2]s %[1]s
`

// script emits the registration for the name this binary was invoked
// as; the baking decision (single-applet / busybox symlink / selector
// mode) is the shared generation policy in the script package.
func script(w io.Writer, src engine.Source, argv0 string) {
	name := strings.TrimSuffix(filepath.Base(argv0), ".exe")
	baked := ""
	if id := genscript.BakedApplet(src, name); id != "" {
		baked = " --applet " + id
	}
	fn := "_sxcli_" + genscript.Sanitize(name)
	fmt.Fprintf(w, scriptTemplate, name, fn, baked)
}

// answer serves one completion query: slice the true tokens at the
// cursor, ask the engine, print _describe pairs. Values have their
// colons escaped (the _describe separator); the description is the
// candidate's one-line doc rendered through Tr, zsh's whole point.
func answer(w io.Writer, src engine.Source, cfg config, words []string) {
	q := engine.Query{Applet: cfg.Applet, Current: cfg.Current}
	if cfg.CWord >= 1 && cfg.CWord <= len(words) {
		q.Words = words[1:cfg.CWord]
	} else if len(words) > 1 {
		q.Words = words[1:]
	}
	for _, cand := range engine.Complete(src, q) {
		if cand.Kind == engine.KindFiles {
			fmt.Fprintln(w, "\x01files")
		} else if cand.Kind == engine.KindDirs {
			fmt.Fprintln(w, "\x01dirs")
		} else {
			line := strings.ReplaceAll(cand.Value, ":", `\:`)
			if doc := oneLine(sxclifw.Tr(cand.Doc)); doc != "" {
				line += ":" + doc
			}
			fmt.Fprintln(w, line)
		}
	}
}

// oneLine reduces a possibly long-form doc to _describe's line format:
// first line only, trimmed.
func oneLine(s string) string {
	if k := strings.IndexByte(s, '\n'); k >= 0 {
		s = s[:k]
	}
	return strings.TrimSpace(s)
}
