// Copyright 2026 Plamen K. Kosseff
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package bash

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"sxcli.dev/completion/engine"
	genscript "sxcli.dev/completion/script"
	"sxcli.dev/fw"
)

// The core's Introspector must keep satisfying the engine's Source —
// this line is the module's whole dependency on that fact, checked at
// compile time.
var _ engine.Source = (*fw.Introspector)(nil)

// defaultBreaks is bash's stock COMP_WORDBREAKS, the assumption when a
// query arrives without --breaks (manual invocation; the generated
// script always passes the real value).
const defaultBreaks = " \t\n\"'><=;|&(:"

// ID is the package's public handle: name it in a composition's
// Accept to include bash completion in the binary.
const ID = "sxcli.dev/completion/bash"

func init() {
	fw.NewRegistration(ID, func() *Completion {
		return &Completion{cfg: config{Version: 1, Breaks: defaultBreaks}}
	}, func(c *Completion) *config { return &c.cfg }).
		Alias("completionbash").
		System().
		Metadata(&fw.Metadata{
			Description: "bash completion for this binary: --script prints the registration script for the name the binary was invoked as, completion queries arrive as raw COMP_WORDS/COMP_CWORD and are answered one candidate per line on stdout",
		}).
		Register()
}

// Configured validates nothing: the query fields are per-invocation
// transport with no illegal states the parser does not already refuse.
func (c *Completion) Configured() error { return nil }

// Run answers the operation selected by the arguments: --script
// emission, or a completion query. Queries always exit 0 — a
// completion must never look like a failure.
func (c *Completion) Run() int {
	if c.cfg.Script {
		script(os.Stdout, c.I, os.Args[0])
	} else {
		answer(os.Stdout, c.I, c.cfg, c.cfg.Words)
	}
	return 0
}

// scriptTemplate is the emitted registration: deliberately dumb bash.
// It forwards raw completion state and renders the answer; the file
// and directory directives arrive as \001-sentinel lines and map to
// the shell's own compgen. -o default keeps undeclared values on the
// shell's file completion, per the engine's silence contract.
const scriptTemplate = `# bash completion for %[1]s, generated by: %[1]s completionbash --script
%[2]s() {
    local IFS=$'\n'
    local -
    set -f
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local line
    COMPREPLY=()
    for line in $("${COMP_WORDS[0]}" completionbash%[3]s --cword "$COMP_CWORD" --line "$COMP_LINE" --breaks "$COMP_WORDBREAKS" -- "${COMP_WORDS[@]}" 2>/dev/null); do
        case "$line" in
            $'\001files') COMPREPLY+=( $(compgen -f -- "$cur") ) ;;
            $'\001dirs')  COMPREPLY+=( $(compgen -d -- "$cur") ) ;;
            *) COMPREPLY+=( "$line" ) ;;
        esac
    done
}
complete -o default -F %[2]s %[1]s
`

// script emits the registration for the name this binary was invoked
// as; the baking decision (single-applet / busybox symlink / selector
// mode) is the shared generation policy in the script package.
func script(w io.Writer, src engine.Source, argv0 string) {
	name := strings.TrimSuffix(filepath.Base(argv0), ".exe")
	baked := ""
	if id := genscript.BakedApplet(src, name); id != "" {
		baked = " --applet " + id
	}
	fn := "_sxcli_" + genscript.Sanitize(name)
	fmt.Fprintf(w, scriptTemplate, name, fn, baked)
}

// answer serves one completion query: reassemble the words bash tore
// apart, slice at the cursor, ask the engine, print. One candidate per
// line; the file/directory directives become sentinel lines for the
// script. Printed values are relative to the word segment bash will
// actually replace — everything after the last :/= break in the
// current token (the __ltrim_colon_completions treatment, generalized
// from the shipped bash-completion).
func answer(w io.Writer, src engine.Source, cfg config, raw []string) {
	words, cur := reassemble(raw, cfg.CWord, cfg.Line, cfg.Breaks)
	q := engine.Query{Applet: cfg.Applet}
	if cur >= 1 && cur < len(words) {
		q.Current = words[cur]
		q.Words = words[1:cur]
	} else if len(words) > 1 {
		// the cursor is past the transported words: a fresh word at
		// the end of the line
		q.Words = words[1:]
	}
	// The engine works on true tokens; bash replaces only the segment
	// after the last break it split on. trim converts one to the other.
	brk := ""
	if strings.Contains(cfg.Breaks, ":") {
		brk += ":"
	}
	if strings.Contains(cfg.Breaks, "=") {
		brk += "="
	}
	trim := ""
	if i := strings.LastIndexAny(q.Current, brk); brk != "" && i >= 0 {
		trim = q.Current[:i+1]
	}
	// FIRST = — the same cut the engine's semantic split makes; an
	// Allowed value containing '=' must not eat into the prefix
	eq := strings.Index(q.Current, "=")
	for _, cand := range engine.Complete(src, q) {
		if cand.Kind == engine.KindFiles {
			fmt.Fprintln(w, "\x01files")
		} else if cand.Kind == engine.KindDirs {
			fmt.Fprintln(w, "\x01dirs")
		} else {
			// values completed through --name= come from the engine
			// bare; rebuild the full token before segmenting so the
			// trim math has one shape for every candidate
			full := cand.Value
			if cand.Kind == engine.KindValue && eq >= 0 && strings.HasPrefix(q.Current, "-") {
				full = q.Current[:eq+1] + cand.Value
			}
			fmt.Fprintln(w, strings.TrimPrefix(full, trim))
		}
	}
}

// reassemble undoes bash's COMP_WORDBREAKS splitting for ":" and "=":
// bash hands "--debug=fal" over as three words ("--debug", "=", "fal")
// and "unix:/dev/log" as ("unix", ":", "/dev/log"); the parser's token
// is the joined form. This is a faithful port of bash-completion's
// _comp__reassemble_words: the original line decides whether a
// separator was glued to its neighbours ("--addr:8080") or stands
// alone ("--addr :8080"), separators never glue onto word 0 (the
// command), and only separators actually present in the shell's break
// set are excluded. The returned index locates the cursor's word in
// the joined list, -1 when cword lies beyond the transported words.
func reassemble(raw []string, cword int, line, breaks string) ([]string, int) {
	exclude := ""
	for _, ch := range ":=" {
		if strings.ContainsRune(breaks, ch) {
			exclude += string(ch)
		}
	}
	var out []string
	cur := -1
	set := func(j int, s string) {
		for len(out) <= j {
			out = append(out, "")
		}
		out[j] += s
	}
	if exclude == "" {
		// the shell never split on :/=; words are already true tokens
		out = append(out, raw...)
		if cword >= 0 && cword < len(raw) {
			cur = cword
		}
	} else {
		pureSeps := func(s string) bool {
			ok := s != ""
			for i := 0; i < len(s) && ok; i++ {
				ok = strings.IndexByte(exclude, s[i]) >= 0
			}
			return ok
		}
		blank := func(s string) bool {
			return strings.HasPrefix(s, " ") || strings.HasPrefix(s, "\t")
		}
		strip := func(l, w string) string {
			if k := strings.Index(l, w); k >= 0 {
				l = l[k+len(w):]
			}
			return l
		}
		j := -1
		for i := 0; i < len(raw); i++ {
			j++
			ended := false
			for i > 0 && !ended && pureSeps(raw[i]) {
				// a glued separator (no whitespace before it on the
				// line) joins the previous word — but never word 0
				if !blank(line) && j >= 2 {
					j--
				}
				set(j, raw[i])
				if i == cword {
					cur = j
				}
				line = strip(line, raw[i])
				if i < len(raw)-1 {
					i++
					// whitespace after the separator starts a new word
					if blank(line) {
						j++
					}
				} else {
					ended = true
				}
			}
			if ended {
				i = len(raw)
			} else {
				set(j, raw[i])
				line = strip(line, raw[i])
				if i == cword {
					cur = j
				}
			}
		}
	}
	return out, cur
}
