// Copyright 2026 Plamen K. Kosseff
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package bash

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"sxcli.dev/completion/internal/engine"
	sxclifw "sxcli.dev/fw"
)

// The core's Introspector must keep satisfying the engine's Source —
// this line is the module's whole dependency on that fact, checked at
// compile time.
var _ engine.Source = (*sxclifw.Introspector)(nil)

func init() {
	c := &Completion{}
	sxclifw.Register("completionbash", c,
		sxclifw.System(),
		sxclifw.WithConfig(&c.cfg),
		sxclifw.WithMetadata(&sxclifw.Metadata{
			Description: "bash completion for this binary: --script prints the registration script for the name the binary was invoked as, completion queries arrive as raw COMP_WORDS/COMP_CWORD and are answered one candidate per line on stdout",
		}),
	)
}

// Configured validates nothing: the query fields are per-invocation
// transport with no illegal states the parser does not already refuse.
func (c *Completion) Configured() error { return nil }

// Run answers the operation selected by the arguments: --script
// emission, or a completion query. Queries always exit 0 — a
// completion must never look like a failure.
func (c *Completion) Run() int {
	if c.cfg.Script {
		script(os.Stdout, c.I, os.Args[0])
	} else {
		answer(os.Stdout, c.I, c.cfg.Applet, c.cfg.CWord, sxclifw.Positionals())
	}
	return 0
}

// scriptTemplate is the emitted registration: deliberately dumb bash.
// It forwards raw completion state and renders the answer; the file
// and directory directives arrive as \001-sentinel lines and map to
// the shell's own compgen. -o default keeps undeclared values on the
// shell's file completion, per the engine's silence contract.
const scriptTemplate = `# bash completion for %[1]s, generated by: %[1]s completionbash --script
%[2]s() {
    local IFS=$'\n'
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local line
    COMPREPLY=()
    for line in $("${COMP_WORDS[0]}" completionbash%[3]s --cword "$COMP_CWORD" -- "${COMP_WORDS[@]}" 2>/dev/null); do
        case "$line" in
            $'\001files') COMPREPLY+=( $(compgen -f -- "$cur") ) ;;
            $'\001dirs')  COMPREPLY+=( $(compgen -d -- "$cur") ) ;;
            *) COMPREPLY+=( "$line" ) ;;
        esac
    done
}
complete -o default -F %[2]s %[1]s
`

// script emits the registration for the name this binary was invoked
// as — generation THROUGH a name decides for that name, once:
//
//   - single-applet mode: no baking; any name runs the sole applet and
//     the engine resolves it per query.
//   - the name is a public applet (a symlink in the busybox farm): the
//     target is baked in as --applet; dispatch rule 4 would run
//     exactly it.
//   - anything else — the real binary's own name included: selector
//     logic stays live, matching dispatch rules 3–4 (an explicitly
//     typed applet id completes; names are offered from the public
//     list only).
func script(w io.Writer, src engine.Source, argv0 string) {
	name := strings.TrimSuffix(filepath.Base(argv0), ".exe")
	baked := ""
	if _, single := src.SingleApplet(); !single {
		for _, id := range src.Applets() {
			if id == name {
				baked = " --applet " + name
			}
		}
	}
	fn := "_sxcli_" + sanitize(name)
	fmt.Fprintf(w, scriptTemplate, name, fn, baked)
}

// sanitize turns an arbitrary command name into a bash function name
// suffix.
func sanitize(name string) string {
	var b strings.Builder
	for i := 0; i < len(name); i++ {
		ch := name[i]
		if (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') {
			b.WriteByte(ch)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

// answer serves one completion query: reassemble the words bash tore
// apart, slice at the cursor, ask the engine, print. One candidate per
// line; the file/directory directives become sentinel lines for the
// script.
func answer(w io.Writer, src engine.Source, applet string, cword int, raw []string) {
	words, cur := reassemble(raw, cword)
	q := engine.Query{Applet: applet}
	if cur >= 1 && cur < len(words) {
		q.Current = words[cur]
		q.Words = words[1:cur]
	} else if len(words) > 1 {
		// the cursor is past the transported words: a fresh word at
		// the end of the line
		q.Words = words[1:]
	}
	for _, cand := range engine.Complete(src, q) {
		if cand.Kind == engine.KindFiles {
			fmt.Fprintln(w, "\x01files")
		} else if cand.Kind == engine.KindDirs {
			fmt.Fprintln(w, "\x01dirs")
		} else {
			fmt.Fprintln(w, cand.Value)
		}
	}
}

// reassemble undoes bash's COMP_WORDBREAKS splitting for "=": bash
// hands "--debug=fal" over as three words ("--debug", "=", "fal");
// the parser's token is the joined form. The returned index locates
// the cursor's word in the joined list, -1 when cword lies beyond the
// transported words.
func reassemble(raw []string, cword int) ([]string, int) {
	var out []string
	cur := -1
	for k := 0; k < len(raw); k++ {
		if len(out) > 0 && (raw[k] == "=" || raw[k-1] == "=") {
			out[len(out)-1] += raw[k]
		} else {
			out = append(out, raw[k])
		}
		if k == cword {
			cur = len(out) - 1
		}
	}
	return out, cur
}
